### ISSUE TITLE
Are language tags correct?

### ISSUE THREAD

**Issue by drgrigg** [btaylor8/james-branch-cabell_figures-of-earth#1]
The chapters are tagged en-GB, but the spelling seems to be American, eg color, honor, are spelled the American way. Though I also see centre rather than center? I haven't tested for others.

**Comment by btaylor8** [comment]
I agree there were some ambiguous spellings, but most of them do tend to be en-US, so I changed them (see commit 80849267bdf7f308f3c0a653516d94a8d89d287d). I did look back at the other Cabell productions, and 2 are en-US, 1 is en-GB.
